{% set name = "legend-pygeom-tools" %}
{% set version = "0.0.19" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/legend_pygeom_tools-{{ version }}.tar.gz
  sha256: dce7670d486ea3f44e1284b1cd6a6cd3f65970b7ff2826f80cf0f0de11ae2dfd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2
    - setuptools-scm >=7
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pint
    - pyg4ometry
    - dbetto
    - legend-pydataobj >=0.15.0

test:
  imports:
    - pygeomtools
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Python tools to handle Monte Carlo simulation geometry
  home: https://github.com/legend-exp/legend-pygeom-tools
  license: GPL-3.0-only
  license_file: LICENSE
  doc_url: https://legend-pygeom-tools.readthedocs.io
  dev_url: https://github.com/legend-exp/legend-pygeom-tools

extra:
  recipe-maintainers:
    - gipert
    - ManuelHu
